### PR TITLE
Added DisableAutomaticReload option

### PR DESCRIPTION
**Pull request by pas-de-2**
Fulfills one of the requests in https://github.com/nipkownix/re4_tweaks/issues/469

Test build:
[dinput8.zip](https://github.com/nipkownix/re4_tweaks/files/10961759/dinput8.zip)

### CODE REVIEW

**Comment by nipkownix** [comment]
Nice! Have you had the chance to test every weapon with this enabled, btw?

**Comment by pas-de-2** [comment]
Yeah, should be good.

**Comment by juuuulian-s** [comment]
this feature has been so fun to play around with. i keep getting hit cuz i forgot to reload, its great!

**Comment by pas-de-2** [comment]
Yeah, I think there's something satisfying about hearing the empty mag click sound and then having to make a decision. The auto reload takes that away, and sometimes even gets you in trouble.

**Pull request merged**
