### PR TITLE
Added Professional mode select for Separate Ways

### PR DESCRIPTION
**Pull request by pas-de-2**
Fulfill's half of https://github.com/nipkownix/re4_tweaks/issues/370

I put this in a TitleMenu.cpp, figured we could start migrating some of the other title-related stuff from Misc.cpp there.

### CODE REVIEW

**Comment by FutonGama** [comment]
Good work with that good stuff. Talking about that, do you think is possible to disable Normal difficult? Cause many players who play the mods choose normal but the modders always make the mod for play on professional. I Have enable the option to disable Easy so i imagined if can be possible disable normal too. Of Course with a box on tweeks to choose if want keep the dificulty on the title or not.

**Comment by nipkownix** [comment]
Pretty nice work! Also, nice call with ``TitleMenu.cpp``.

**Comment by nipkownix** [comment]
Are both ``isAssignmentAda`` and ``isMercenaries`` supposed to be checking ``SYS_OMAKE_ADA_GAME``?

**Comment by pas-de-2** [comment]
Nope, lol, good catch.

**Comment by nipkownix** [comment]
(Pushed a small menu-related feature here, since this is where we're moving things to TitleMenu.cpp)

Also tried looking at the Assignment Ada thing, but couldn't think of any decent way to do it.
Could _maybe_ just create our own textures to show there instead, but.. maybe it would be best to just add options in the .ini/cfgMenu to force difficulties for Separate Ways and Assignment Ada? That would at least make Professional Assignment Ada possible for now.

**Comment by pas-de-2** [comment]
Nice tweak!

I wasn't *too* fussed about Assignment Ada, because it's sort of a mini-Professional mode already, in that it has no adaptive difficulty. But yeah some kind of .ini option could be good for those who really want it.

If we added `ForceProfessional` as a variable for modders, people could also just use that as a workaround for now?

**Comment by nipkownix** [comment]
Pushed a new option to override the difficulty on any game mode. Should be enough for modders, I think. Doesn't affect existing saves, but I don't think that's a problem.

This got me thinking, though: Should ``OverrideCostumes`` and ``OverrideDifficulty`` be moved to the Trainer tab now? What do you think, @emoose?

Also, maybe ``SeparateWaysDifficultyMenu`` should be enabled by default.

**Comment by emoose** [comment]
>Should OverrideCostumes and OverrideDifficulty be moved to the Trainer tab now? What do you think, @emoose?

Yeah that sounds good to me, I guess they could be added to Patches section, unless we want to make another Overrides tab for those? (could probably move speed/HP override stuff there too?)

Patches is starting to fill up quickly too, was thinking of merging some of the cheat-ish patches into a single column section, with the descriptions as tooltips, would free up some space but haven't tried it yet though, not sure if it might look janky or something lol.

**Comment by pas-de-2** [comment]
I added checks to the `SkipLevelSelect` and `titleAda_levelMenu` structs to skip the difficulty menus whenever OverrideDifficulty is set.

Making `SeparateWaysDifficultyMenu` default sounds good to me 👍

**Comment by nipkownix** [comment]
> Yeah that sounds good to me, I guess they could be added to Patches section, unless we want to make another Overrides tab for those? (could probably move speed/HP override stuff there too?)

Making an Overrides tab sounds nice. Will take a look at it soon.

Guess we should be safe to merge this. Many thanks for your work here, @pas-de-2!

**Pull request merged**
