### PR TITLE
Trainer: GUI for trainer related patches / enemy data editing

### PR DESCRIPTION
**Pull request by emoose**
As mentioned at https://github.com/nipkownix/re4_tweaks/issues/243#issuecomment-1181395554

Added a quick GUI for editing data of `cEm` instances, also added some trainer patches to it as well, currently includes an Invincibility patch & a 1-shot-kill weak enemies patch - both patches are linked up to debug flags so the tool menu flag editor should be able to enable them too (maybe in future we could add a way to bind certain flags to hotkeys too, or something like that)

E: also added a infinite ammo patch, thanks to @Mister-Curious for providing the bytes for it!

bio4_22-07-12_17-22-59

**This is currently a draft PR since we're still waiting on #257 to be tested**/merged, which this includes some of the GUI changes from, once that's merged I'll probably redo this branch again.

Only really tested with 1.1.0 so far, but everything is sig scanned etc, so hopefully should work on other versions too.

Also interested in any requests for things to add to this section, or any ideas on best way to save/load `cEm` changes, not really sure how to handle that atm.
(main issue is that there's no way to uniquely ID a cEm... afaik cEms can get loaded into any slot, so can't rely on the index of it to know where to load modded values into, also cEms can be created/destroyed any time during play, so the cEm being changed might not even exist when level is loaded)

### CODE REVIEW

**Comment by DarkxVoid-loop** [comment]
when i can figure out a way to save the changes it will be perfect, by far the biggest and best update so far

**Comment by FutonGama** [comment]
I hope you discover a way to save that, luis webber make it save using the INI

**Comment by Mister-Curious** [comment]
Thanks for this. Its looking good. I did provide you with a big list of edits in your inbox on the forums a while ago. Were some of those not working? I don't see a lot of those present here:

No Enemy Spawn
No BGM
Invincibility
Infinite Ammo
Disable Collision
Always XL Attache Case
No Leon Model In Inventory
Bodies do not disappear 

All the code is in that message thread. Glad to see this coming to life!

**Comment by nipkownix** [comment]
Looks awesome!

>(main issue is that there's no way to uniquely ID a cEm... afaik cEms can get loaded into any slot, so can't rely on the index of it to know where to load modded values into, also cEms can be created/destroyed any time during play, so the cEm being changed might not even exist when level is loaded)

Yeah, I was about to mention that.
Not sure if trying to save this stuff is the best way to go, as I imagine there are too many things we have to predict/assume.
Unless we went with something more generic such as ``if EmTypeXX, apply Speed *= 2`` or something like that.
Depends on what people are expecting to achieve with this, I guess.

**Comment by DarkxVoid-loop** [comment]
we modders want to be able to edit the size and speed of our esl enemies, it's the most wanted function for us, we just want to edit 1 time and save for our mods to be complete

**Comment by DarkxVoid-loop** [comment]
And who knows being able to do the ESL and maybe the ITA and ETS too because this trainer can put this in game would be perfect

**Comment by nipkownix** [comment]
Are ESL, ITA, ETS, etc, file extensions? If so, it would be better to find a way to edit those files directly, instead of trying to save memory changes like this.

**Comment by DarkxVoid-loop** [comment]
Yes they are file extension, I don't know how Raz0r did it but in compenion it saves the ini in notepad to keep the changes

**Comment by Mister-Curious** [comment]
>we modders want to be able to edit the size and speed of our esl enemies, it's the most wanted function for us

I would say that while this is a feature some have requested, it is certainly not 'the most wanted function'. There are plenty of things we still need that would be much more useful than that.

**Comment by Mister-Curious** [comment]
> Are ESL, ITA, ETS, etc, file extensions? If so, it would be better to find a way to edit those files directly, instead of trying to save memory changes like this.

Yes they are file extensions, and there are tools for these files (and ample tutorials) on how to use them.

**Comment by DarkxVoid-loop** [comment]
> 

that's what's missing in our mods Raz0r managed to save it but with it's encrypted it's not possible to find out, but that would make our mods more complete they would

**Comment by FutonGama** [comment]
> Looks awesome!
> 
> > (main issue is that there's no way to uniquely ID a cEm... afaik cEms can get loaded into any slot, so can't rely on the index of it to know where to load modded values into, also cEms can be created/destroyed any time during play, so the cEm being changed might not even exist when level is loaded)
> 
> Yeah, I was about to mention that. Not sure if trying to save this stuff is the best way to go, as I imagine there are too many things we have to predict/assume. Unless we went with something more generic such as `if EmTypeXX, apply Speed *= 2` or something like that. Depends on what people are expecting to achieve with this, I guess.

Its not a problem be something more generic, change the enemy speed and size is one of the most request thing by modders, luis webber is the only one who do that and never shared with the comunity and we always try to discover a way but no success by years. Me, JM, kTeo, DarkxVoid, Scoovy, Adam, Ashe, Waly, Higo, Leo Lima, every of these modders are trying figure out how to do that and is very frustrating. kTeo have discovered two codes for enemy size for the Garrador and Mega but only that two and nothing about the speed. Its not a problem to me if be generic or more complexy way to do that, can be very nice to have it simple or not, when i see this complexy way that emoose made i'm have cryed, this is important for the mods alot. Now i will speak portuguese for Nipkownix because i know he is Brazilian. Mano, resumindo aqui em portugues pq fica mais facil de eu explicar, tamo geral tantando descobrir isso a um século ja e nada de achar a velocidade e tamanho dos inimigos, quando vi isso dai q o emoose fez eu fiquei maluco, adorei, se criar algo mais simples ta bom d+ já, vai todo mundo já ficar feliz.

**Comment by emoose** [comment]
Maybe if we can find the code that handles creating `cEm` from the ESL list, we could tie the changes to the index inside the ESL, assuming that the cEms that people want to modify are all from ESL that should probably work.

I've never really looked into the ESL stuff before though, so no idea where that's handled in the code yet.

**Comment by nipkownix** [comment]
> Mano, resumindo aqui em portugues pq fica mais facil de eu explicar, tamo geral tantando descobrir isso a um século ja e nada de achar a velocidade e tamanho dos inimigos, quando vi isso dai q o emoose fez eu fiquei maluco, adorei, se criar algo mais simples ta bom d+ já, vai todo mundo já ficar feliz.
> 
> Ah e já agradeço muito, Thank You!

Só fiquei meio confuso pq Mister-Curious falou ali que existem algumas tools que editam aqueles arquivos lá. Essas tools não servem pra mudar essas coisas? Se aquele luis webber conseguiu, imagino que ele editou os arquivos, ao invés de editar a memória do jogo. Estranho ele não ter compartilhado com o resto da comunidade...

**Comment by FutonGama** [comment]
> 

Nunca achamos qual arquivo mexe com o tamanho, o kTeo achou pelo HEX como mudar o Garrador e Mega. Quanto ao Luis ele é apenas egoista, diz que é programador e que passaria as coisas, mas era promessa atrás de promessa por anos, bloqueou a DLL dele pra ninguém usar e nunca passou nada pra comunidade e assim que todos descobrem algo q ele ja tinha a anos ele em seguida revela como faz pra parecer um bom samaritano, enquanto isso todos aqui se esforçando pra não chegar a nenhum lugar. Com isso os mods dele sempre estão no topo, como o Life in Hell, Rising of Evil e Arrange e a gente se esforçando pra não ter metade do reconhecimento. Bem ao contrário de nós que soltamos tudo que aprendemos na Remodding, tem tudo la, só procurar por coisas do kTeo, minhas, do Curious, mas nada do Luis dês de anos.

**Comment by FutonGama** [comment]
> Maybe if we can find the code that handles creating `cEm` from the ESL list, we could tie the changes to the index inside the ESL, assuming that the cEms that people want to modify are all from ESL that should probably work.
> 
> I've never really looked into the ESL stuff before though, so no idea where that's handled in the code yet.
> 
> E: oh looks like ESL might be related to `EM_LIST` stuff I added in way back, https://github.com/nipkownix/re4_tweaks/blob/master/dllmain/Game.h#L194
> 
> Would still need to find where the cEm is created first though.

Looking foward to it.

xx

Its not possible to use the last 4 Columns of the ESL for edit the size and speed? This bytes is blank

**Comment by emoose** [comment]
Hmm nice idea, maybe possible to add that, if we can find all the parts that read from the EM_LIST stuff.

So far I've seen two methods, `EmSetEvent` seems to read all the data out of EM_LIST and creates a new cEm from it, and `GetEmIdFromList` seems to return the EmXX ID from EM_LIST, and game either passes that ID to `EmReadSearch` which I guess creates a new cEm from it, or passes it to `EventMgr::EvtRead`.

`EmSetEvent` might be pretty easy to update, but not sure about the second one though, not really sure how that second method could be getting stuff like position etc out of the EM_LIST, if it's only being given the ID...

**Comment by FutonGama** [comment]
OK

> Hmm nice idea, maybe possible to add that, if we can find all the parts that read from the EM_LIST/ESL stuff.
> 
> So far I've seen two methods, `EmSetEvent` seems to read all the data (position, rotation, HP) out of EM_LIST and creates a new cEm from it, and `GetEmIdFromList` seems to return the EmXX ID from EM_LIST, and game either passes that ID to `EmReadSearch` which I guess creates a new cEm from it, or passes it to `EventMgr::EvtReadXXXX`.
> 
> `EmSetEvent` might be pretty easy to update to read stuff from those bytes, but not sure about the second one though, not really sure how that second method could be getting stuff like position etc out of the EM_LIST, if it's only being given the ID...
> 
> There are only 4 bytes there though, scale & size would need 8 bytes to store full float values for them. I guess we could split them into 2 bytes each and maybe hold a percentage value for them instead, or maybe see if there's a 16-bit half-float impl. we can add in, not sure if many hex editors support half-floats though, so guess percentage would be easier to edit.

Ok try percentage

**Comment by FutonGama** [comment]
> 



> OK
> 
> > Hmm nice idea, maybe possible to add that, if we can find all the parts that read from the EM_LIST/ESL stuff.
> > So far I've seen two methods, `EmSetEvent` seems to read all the data (position, rotation, HP) out of EM_LIST and creates a new cEm from it, and `GetEmIdFromList` seems to return the EmXX ID from EM_LIST, and game either passes that ID to `EmReadSearch` which I guess creates a new cEm from it, or passes it to `EventMgr::EvtReadXXXX`.
> > `EmSetEvent` might be pretty easy to update to read stuff from those bytes, but not sure about the second one though, not really sure how that second method could be getting stuff like position etc out of the EM_LIST, if it's only being given the ID...
> > There are only 4 bytes there though, scale & size would need 8 bytes to store full float values for them. I guess we could split them into 2 bytes each and maybe hold a percentage value for them instead, or maybe see if there's a 16-bit half-float impl. we can add in, not sure if many hex editors support half-floats though, so guess percentage would be easier to edit.
> 
> Ok try percentage, try to put 00 be Default size and speed

**Comment by emoose** [comment]
Seem to have it mostly working, here's a test build:
[dinput8-emListParamExtension.zip](https://github.com/nipkownix/re4_tweaks/files/9108623/dinput8-emListParamExtension.zip)

The first 2 unused bytes in highlighted part of https://github.com/nipkownix/re4_tweaks/pull/266#issuecomment-1183939200 are treated as speed percentage, last 2 as size percentage, (eg set to 200 to make them 2x, 50 for 0.5x, etc)

Only tested with 1.1.0 but hopefully sigs will match other versions too.
If you find an enemy that isn't being affected by it let me know!

**Comment by FutonGama** [comment]
Amazing, i will test it now!! Thank You so much!

**Comment by FutonGama** [comment]
https://www.youtube.com/watch?v=w5HY5FQ1jVI ITS WORKING, IM HAPPY ASF!!

**Comment by emoose** [comment]
Small fixup, seems game can use hardcoded `EM_LIST` structs inside the EXE, they don't set up all the fields for it though, which results in 0xA / 0x1C getting random stack data instead (this happens with the first guy in R100, and looks like a couple other spots too)

Will now check to make sure the `EM_LIST` came from an ESL file instead before we use scale/speed from it, also added ESL filename to the Em manager so you can know which ESL spawned the enemy 😄 

Build soon at https://github.com/nipkownix/re4_tweaks/actions/runs/2668696089

**Comment by kTeo-0** [comment]
We tested the speed/size functions with all enemies, this is the result:

03 00 WORKS BOTH
A3 00 WORKS BOTH
A4 00 WORKS BOTH
em10 SPEED ONLY
em11 SPEED ONLY
em12 SPEED ONLY
em13 SPEED ONLY
em14 SPEED ONLY
em15 SPEED ONLY
em16 SPEED ONLY
em17 SPEED ONLY
em18 BOTH WORKS
em19 SPEED ONLY
em1a SPEED ONLY
em1b SPEED ONLY
em1c SPEED ONLY
em1d SPEED ONLY
em1e SPEED ONLY
em1f SPEED ONLY
em20 SPEED ONLY
em21 BOTH WORKS
em22 BOTH WORKS
em23 SPEED ONLY
em24 SPEED ONLY
em25 BOTH WORKS (only by direct spawning. Only speed works when spawning by ganado plaga)
em26 BOTH WORKS
em27 SPEED ONLY
em28 BOTH WORKS
em29 SPEED ONLY
em2a ??? (bear traps does not work straight away, only when they get activated. Explosive traps works well)
em2b BOTH WORKS
em2c BOTH WORKS
em2d BOTH WORKS
em2e BOTH WORKS
em2f BOTH WORKS
em30 BOTH WORKS
em31 BOTH WORKS
em32 BOTH WORKS
em34 BOTH WORKS
em35 BOTH WORKS
em36 BOTH WORKS
em38 BOTH WORKS
em39 BOTH WORKS
em3a BOTH WORKS
em3b BOTH WORKS
em3c SPEED ONLY
em3d BOTH WORKS
em3f SPEED ONLY (speed change bugged due to lack of SEQ files)
em40 SPEED ONLY
em41 SPEED ONLY
em42 SPEED ONLY
em43 SPEED ONLY
em44 SPEED ONLY
em45 SPEED ONLY
em4e BOTH WORKS
emcc BOTH WORKS

**Comment by FutonGama** [comment]
> Hm, that's from changing it with ESL or from Em manager?
> 
> Looks like some Ems overwrite the scale during their `emXX_R0_Init` function, after our ESL hooks have been ran... maybe could get it to force the scale each frame for ones that have it set, will try having a look.

So for this Em Manager is not saving the changes for "ESL-spawned only" right?

**Comment by emoose** [comment]
Might have a solution for the EmXX_R0_Init issue, just made it so before we apply the scale/speed changes it calls em->move() if the Em needs to init first, move() should then let it init and change state so it won't use init function anymore, then we update scale/speed after that and hopefully it'll stay in-place.
(some Ems might change scale/speed in other non-init funcs though, can't really do much for those...)

Test build if anyone wants to try it out:
[dinput8-emListParamExtension-initFixTest.zip](https://github.com/nipkownix/re4_tweaks/files/9110744/dinput8-emListParamExtension-initFixTest.zip)
Should hopefully let more Ems work with it, haven't seen any issues caused by calling em->move() early like this yet.

>So for this Em Manager is not saving the changes for "ESL-spawned only" right?

Em Manager should be able to update changes onto the game being played for both ESL & non-ESL Ems, but there's nothing to save it to file or anything like that.

**Comment by emoose** [comment]
The gdrive link gives me "We're sorry. You can't access this item because it is in violation of our Terms of Service" :/

I'm not really sure about trying to make it work with another DLL mod, depends how he handles the ESL I guess, if he's calling the games normal EmList funcs with it then I guess he'd just need to make sure to include the 0xA/0x1C bytes...
Then again I did add that check to make sure it's from ESL file which would probably stop that working - maybe worth testing a build from before I added that check and see if that works? (the v4 build should be fine)

**Comment by Mister-Curious** [comment]
I can say this works fine with the Companion DLL side-chaining ESL files. It might be worth trying to accommodate the **enemy_swap.ini** feature that is used by the DLL to allow scaling of enemies that are spawned with this feature. I'm still trying to think of a value in the .ini file that we could use... Perhaps a custom health value or something. 

I might ask my friend to look into this too, as he recently created a way to spawn enemies with the AEV & ITA working together (it's not capable of issuing health though, so some may not want to use it), however since it is a hardcoded edit to the binary, it would be compatible with other DLLs. It might be as easy as assigning some ITA bytes to write to those ESL bytes @emoose drafted.

**Comment by Mister-Curious** [comment]
One issue though is the collision not scaling with the enemy, so for example, if you make a smaller El Gigante  the collision is still for a big enemy. Scaling enemy collision isn't easy as there are often shared values across various enemies so scaling for one, might affect another. Might be worth checking into though.

**Comment by FutonGama** [comment]
> The gdrive link gives me "We're sorry. You can't access this item because it is in violation of our Terms of Service" :/ If it's a small file you can probably just ZIP it and drag+drop here.
> 
> I'm not really sure about trying to make it work with another DLL mod, depends how he handles the ESL I guess, if he's calling the games normal EmList funcs with it then I guess he'd just need to make sure to include the 0xA/0x1C bytes... Then again I did add that check to make sure it's from ESL file which would probably stop that working - maybe worth testing a build from before I added that check and see if that works? (the v4 build should be fine)
> 
> (If there was a way to know if EM_LIST pointer is from stack or not then I could probably remove that ESL file check altogether, doesn't seem there's any easy way to do that though ;_;)

[Test.zip](https://github.com/nipkownix/re4_tweaks/files/9114159/Test.zip)

The qingsheng DLL with a secondary ESL in r103

**Comment by DarkxVoid-loop** [comment]
Emoose the main thing to do now is that we can edit the secondary esl of qingsheng that it uses the spawn of the mercenaries, the fcv file follows the changes for the collision to be right, and also we can edit and save everything through your tool 

But I will list very important things to get into this your  trainer

Edit case items
Leon's Speed 
door locking 
Free Camera 
Can raise camera altitude 
Teleport between maps 
Edit ETS and ITA by tool 
Push Ashley to you by a button 
Push all enemies around you 
Place hotkeys to select weapons 

All are great additions that would make it perfect and we'd stop using Raz0r's

**Comment by FutonGama** [comment]
> Emoose the main thing to do now is that we can edit the secondary esl of qingsheng that it uses the spawn of the mercenaries, the fcv file follows the changes for the collision to be right, and also we can edit and save everything through your tool
> 
> But I will list very important things to get into this your trainer
> 
> Edit case items Leon's Speed door locking Free Camera Can raise camera altitude Teleport between maps Edit ETS and ITA by tool Push Ashley to you by a button Push all enemies around you Place hotkeys to select weapons
> 
> All are great additions that would make it perfect and we'd stop using Raz0r's

Teleport between maps already have on debug but thats fine. Just to be clear to emoose and others why we always want to be out of Raz0r Trainer, its because this Trainer destroy the game memory for some reason, the game crashes alot with trainer opened.

**Comment by Mister-Curious** [comment]
If there is one Raz0r trainer feature I can not live without it is the ability to navigate the Z axis with hotkeys. I use this feature every time I am testing something (sometimes to get a closer look at something, or to test triggerzone boundaries etc). This feature would be VERY useful to modders who create stage mods.

**Comment by FutonGama** [comment]
> The gdrive link gives me "We're sorry. You can't access this item because it is in violation of our Terms of Service" :/ If it's a small file you can probably just ZIP it and drag+drop here.
> 
> I'm not really sure about trying to make it work with another DLL mod, depends how he handles the ESL I guess, if he's calling the games normal EmList funcs with it then I guess he'd just need to make sure to include the 0xA/0x1C bytes... Then again I did add that check to make sure it's from ESL file which would probably stop that working - maybe worth testing a build from before I added that check and see if that works? (the v4 build should be fine)
> 
> (If there was a way to know if EM_LIST pointer is from stack or not then I could probably remove that ESL file check altogether, doesn't seem there's any easy way to do that though ;_;)

Emoose, do you have discord?

**Comment by emoose** [comment]
Not really sure how far I'm going to go with this really... mostly focused on inspecting/editing things that are in-engine, to hopefully learn more about some unknowns, editing files is kinda out-of-scope here.

(I know another modder is doing some great work documenting the file formats though, hopefully they'll release what they have soon)

Other than that anything that interacts with the engine is still on the table though, will probably work on adding some more of the trainer patches from @Mister-Curious soon, and will probably add some kind of fly-mode similar to the one in the debug build too.

(this branch is still depending on https://github.com/nipkownix/re4_tweaks/pull/257 being merged though, if you want to see this get released properly, please help us test that!)

**Comment by FutonGama** [comment]
> Not really sure how far I'm going to go with this really, mostly focused on inspecting/editing things that are in-engine, to hopefully learn more about some unknowns, editing files is kinda out-of-scope here.
> 
> (I know another modder is doing some great work documenting the file formats though, hopefully they'll release what they have soon)
> 
> Other than that anything that interacts with the engine is still on the table though, will probably work on adding some more of the trainer patches from @Mister-Curious soon, and will probably add some kind of fly-mode similar to the one in the debug build too.
> 
> (this branch is still depending on #257 being merged though, if you want to see this get released properly, please help us test that...)

I can't test things about FPS because my computer is very high end, i don't have slow motions, i will tell to kTeo test the performance more. About the size and speed some of then is not scaling size, kTeo made a list of what is working.

**Comment by emoose** [comment]
We don't really need to test if it fixes slow-motion, just that the game still plays fine with the fix in place, the more people that can try playing through the game with #257 the better.

**Comment by FutonGama** [comment]
> 

Fine i will keep testing

**Comment by emoose** [comment]
Added a setting in trainer to allow noclip-style keypad-movement using the numpad, 2/4/6/8 will move player around, 1/7 will move player up and down, currently it's not affected by camera direction but hoping to fix that soon.

(camera also doesn't seem to get updated properly when moving with numpad, if you hold down the normal walk-forward key while using it that should update camera for you though, will hopefully have a fix soon)

**Comment by nipkownix** [comment]
So, this depends on #257, right? How would I build it locally without merging that one? I wanted to try adding some trainer options myself :p

**Comment by emoose** [comment]
AFAIK you should be able to just check out this branch and build it, the #267 dependency is mainly just the cfgMenu column code update (it's both included here & in 267, so will probably be a pain once 267 is merged heh, was planning on rebasing/redoing this onto master once 267 is in though)

**Comment by emoose** [comment]
Ah whoops accidentally left something unused there, just force-pushed to fix it, if you checked it out you might need to checkout again 😅

**Comment by nipkownix** [comment]
Ahhh, so that must have been why I was having issues :p
Will checkout again. Thanks!

**Comment by emoose** [comment]
Ohh I think the game has some code that clears the debug flags each frame, EnableDebugMenu nops that out IIRC, can probably just move that to Trainer_Init instead, will look into it soon.

**Comment by nipkownix** [comment]
Just pushed an update to the no-clip stuff that I think will improve usability.
It also keeps the collision off if DBG_PL_NOHIT is set, which I believe was the original intent of this flag.
Let me know what you think. You can just revert the commit if you don't think it is a very good approach.

**Comment by FutonGama** [comment]
> "Warning: this section contains cheats & patches that may ruin your game experience, or break things in the game, are you sure you want to use the trainer menu?" 

Feels good

**Comment by nipkownix** [comment]
>Maybe some kind of warning that shows up first time they click it would be fine "Warning: this section contains cheats & patches that may ruin your game experience, or break things in the game, are you sure you want to use the trainer menu?", hmm...

Good idea. Just pushed a commit with this.

**Comment by nipkownix** [comment]
Updated build here:

https://github.com/nipkownix/re4_tweaks/suites/7489440390/artifacts/307455476

@Mister-Curious

**Comment by FutonGama** [comment]
> Updated build here:
> 
> https://github.com/nipkownix/re4_tweaks/suites/7489440390/artifacts/307455476
> 
> @Mister-Curious

I tested, it feels very good. A good thing is put a key to toggle Collision on and off like raz0r Trainer, Default is T.

**Comment by FutonGama** [comment]
> 

Hey Emoose you figure out some way to save changes? Its possible save the changes directly on ESL for the enemies showed when you turn on "ESL-spawned"?. And if possible change the EmXX for Hex, its everything on decimal and feels confusing, Mr Curious enemy IDs list is on hexadecimal and the game files too. I see a lot of future ahead for the game with these in-game tools. RE4 Tweaks is shining! Thx for attention. 

opera_EtjmxznN3t

**Comment by Mister-Curious** [comment]
> I tested, it feels very good. A good thing is put a key to toggle Collision on and off like raz0r Trainer, Default is T.

YES please.. A hot key is a must for this (@emoose thanks)!

**Comment by DarkxVoid-loop** [comment]
@emoose  I really liked your trainer on Re4 tweaks 
These are the options we use the most in the Raz0r trainer, and we want you to implement these options 
Raz0r Trainer Inventory Tab
Pull Ashley to you
Pull all enemies to you 
Leon's Speed 
Disable One-Key Collision

Another thing that would be very useful is that even if you restart the game, the trainer options remain checked

**Comment by Mister-Curious** [comment]
something I would like to add as feedback (and simple request) is when the collision is disabled, that it maintain collision that is on a slope. That is to say, the trainer should not cancel sloped collision. This would allow players to still climb hills, or use stairs (this is the behavior of Raz0r's Trainer). 

Cheers

**Pull request closed without merging**
