### PR TITLE
Created Gameplay tab in ImGui

### PR DESCRIPTION
**Pull request by pas-de-2**
For https://github.com/nipkownix/re4_tweaks/pull/366#issuecomment-1364454566

### CODE REVIEW

**Comment by pas-de-2** [comment]
`UseSprintToggle` and `LimitMatildaBurst` are technically more like controller tweaks. I suppose we could duplicate `UseSprintToggle` in the Keyboard and Controller tabs, and `LimitMatildaBurst` in the Mouse and Controller tabs?

**Comment by nipkownix** [comment]
Moved stuff to a new .cpp file and changes our .ini a bit. Should probably make sure everything still works correctly.. I've messed that up in the past ._.

> UseSprintToggle and LimitMatildaBurst are technically more like controller tweaks. I suppose we could duplicate UseSprintToggle in the Keyboard and Controller tabs, and LimitMatildaBurst in the Mouse and Controller tabs?

Hmm, I think since the implementation for them is the same for KB/M and controllers, leaving them in the Gameplay tab should be fine?

**Comment by pas-de-2** [comment]
Oh, it's a shame that moving settings between tabs resets people's existing config settings. Maybe that's why you were opposed to new tabs?

**Comment by nipkownix** [comment]
> Any reason the ini reader shouldn't just check for the whole file?

Hmm, just to keep things organized, I guess?
It isn't that big a deal IMO. But should probably add a warning in the release changelog mentioning that some settings may have reverted back to default...

**Comment by pas-de-2** [comment]
What about grouping `DisableQTE` and `AutomaticMashingQTE` within the same column, like in https://github.com/nipkownix/re4_tweaks/pull/366#issuecomment-1364454566? I can't tell if you didn't like that or if you just merged over it with your existing changes, heh.

**Comment by nipkownix** [comment]
Oh shoot, I think I may have accidentally overwritten that when changing the order of the settings. Sorry! I does look better.

**Comment by nipkownix** [comment]
Everything looks good to me. Thanks again, @pas-de-2.

**Pull request merged**
