### PR TITLE
AudioTweaks: allows seperate adjustment of BGM / SFX / cutscene volume

### PR DESCRIPTION
**Pull request by emoose**
As requested at #199, went ahead and added volume sliders to a new Audio section in the re4_tweaks UI too (who knows, maybe we'll figure out more audio fixes eventually 😄)

Most kinds of audio can have volume adjusted at runtime, ~~but it seems BGM usually needs to be reloaded first (eg by reloading the level), also added a note about that to the UI.~~

I'd guess the volume values we're adjusting here probably get copied somewhere when that audio starts playing, maybe there's some way to track down where & adjust the volume as it plays (looks like the values might be getting transformed a little first though, so might take some work...)

FMV cutscenes seem to use some Criware audio system instead of the stuff main game uses, but luckily wasn't too hard to adjust that as well.

Seems to work across all the usual EXE versions, haven't tested it that much in-game yet though, would appreciate hearing from anyone that tries it out! (build artifact available at https://github.com/nipkownix/re4_tweaks/actions/runs/2457817918)

Some earlier notes that might still apply:
>not totally sure if all sounds will be affected by it though - would be interested if anyone finds something that doesn't work with it.

>there's also 3 different values for both BGM/SE as well, not completely sure I'm changing all the correct ones, so if you notice some sound effect changing when you adjust BGM, or vice-versa, let me know

E: as noted in the issue linked above, looks like cutscenes don't have BGM/SE separated properly for some reason, all sounds end up being controlled by `str_se` value... maybe this is part of why they never added audio options themselves.
Looks like  BGM/SE both go through the same func to fetch the volume, but a flag check decides what kind it is, maybe there's some way to set up that flag on the cutscene BGM.

E2: looks like that flag originates inside `bio4str.hed` :/ Not sure if the format for that is documented anywhere.

### CODE REVIEW

**Comment by emoose** [comment]
Added a workaround for the cutscene audio, seems `str_se` is mostly only ever used by cutscenes, so moved that over to be affected by BGM slider instead.

Only issue I've noticed is merchant dialog now gets affected by BGM slider too, I guess maybe that's handled same way as cutscenes, not sure if there's any way to change it...

**Comment by emoose** [comment]
Seem to have volume adjustment during playback working, for the `str_*` sounds at least, this seems to let us adjust BGM & cutscene audio fine.

I think certain currently-playing effects still aren't updated though, but since effects don't play for that long it's not a huge issue IMO.

Build artifact at https://github.com/nipkownix/re4_tweaks/actions/runs/2463654847

**Comment by emoose** [comment]
Should have the issue with BGMs fixed, now hopefully all BGMs should be adjustable during playback 😄 

Build artifact at https://github.com/nipkownix/re4_tweaks/actions/runs/2464507044

**Comment by emoose** [comment]
Well there is one small thing I'm not really sure about yet, the `mas_bgm/mas_se` values, it looks like those are master values which the other values are then multiplied by, initially I updated those as well, but removed that so we could have finer control of the other values.

Right now though when the game changes those mas values itself (`SndSubScreenInit`), our `Snd_set_system_vol_Hook` will store the value the game is setting, and then scale that value by the users volume setting to find the new value for `str_se`/`iss_se`/etc.

If the game is scaling those str/iss values by `mas` already though, this would probably end up scaling it by `mas` twice - `SndSubScreenInit` sets `mas` to 1/2 of normal value, so our `UpdateVolume` then scales eg. `iss_bgm` by 1/2, and then the games volume calc code scales `iss_bgm` by `mas`, maybe ending up at 1/4 of volume?

I'm not totally sure how the mas scaling works though, when I first started playing with this it didn't seem like mas influenced the volume at all, but the code does show it's being added in somehow... 

Eh, I'll try having a closer look at it later on, maybe can just remove the code that scales by what game tried to set.

**Comment by emoose** [comment]
Looks like the volume in subscreens was definitely lower with this hook at 100% compared to vanilla game, went ahead and removed the stuff to scale by value set by game, seems better now.

If game ever updated `iss/str` volumes itself then the code for storing that & scaling user volume level by it would probably be useful, but seems game only ever updates the `mas` volume, and since it seems game is already applying scaling for that itself already we don't really need to bother with it.

New build artifact at https://github.com/nipkownix/re4_tweaks/actions/runs/2475491191

**Comment by emoose** [comment]
Should be good to merge now, haven't had any issues in the few times I've tested with it at least.

Only thing missing now is some way of changing volume of certain effects during playback (eg. the sound that game makes as it fades into main menu, not really sure how that sound is being played atm...), but like mentioned before those effects don't seem to play for that long, so not a big deal, but would be nice to eventually get them adjustable...

**Comment by nipkownix** [comment]
Thanks!

**Pull request merged**
