### PR TITLE
Add `EnableDebugMenu` option

### PR DESCRIPTION
**Pull request by emoose**
Figure I should probably make a PR so it's easier to track the changes for this.

This adds the debug menu stuff mentioned in #8 - pretty much everything there has been added here, except for the `LIGHT TOOL` function, I'll look into adding that soon.

I've also made some of the debug-menu fixes here apply to the debug build too, so that can also benefit from some of our patches (fixed `AREA JUMP`, button binding changes, relocated text...), and also adds some hooks to slow down the menus and actually make them usable.

There's still a few things left to add here:
- [x] Debug-build `DEBUG OPTIONS` menus need button bindings changed
- [x] `LIGHT TOOL` (TODO: ~~add Filter00 params~~, add more filters to mess with)
- [x] Figure out why button presses are now being carried across different menus (eg. pressing A to select `AREA JUMP`, will then make the `AREA JUMP` menu also act on the A press, pretty sure this didn't happen before...) - E: this might be keyboard only?
- [x] Add keyboard bindings for the debug build menus
- [ ] Find out if this actually causes heap corruption or not

### CODE REVIEW

**Comment by emoose** [comment]
`LIGHT TOOL` is added :smile:, also added some extra Filter00 tweakables.

I'm still unsure if this can cause heap corruption/crashes or not though.. would appreciate if anyone can give it a try for a couple days and let me know how it goes (shouldn't be any crashes during gameplay, only seems to crash straight after loading a save, so no chance of progress loss hopefully!)

Here's a build of 97e7b85 commit if anyone wants to try: [re4_tweaks-debug_menu-97e7b85.zip](https://github.com/nipkownix/re4_tweaks/files/7572681/re4_tweaks-debug_menu-97e7b85.zip)

Use LS+LT to open menu, or HOME+END

**Comment by emoose** [comment]
`LIGHT TOOL` has been added :smile:, also added some extra Filter00 tweakables.



I'm still unsure if this can cause heap corruption/crashes or not though.. would appreciate if anyone can give it a try for a little while and let me know how it goes (shouldn't be any crashes during gameplay, only seems to crash straight after loading a save, so no chance of progress loss hopefully!)

Here's a build of 6802c89 commit if anyone wants to try: 
[re4_tweaks-debug_menu-6802c89.zip](https://github.com/nipkownix/re4_tweaks/files/7572728/re4_tweaks-debug_menu-6802c89.zip)

Use LS+LT to open menu, or HOME+END.

**Comment by emoose** [comment]
Added a couple more params to edit:



Also mapped out a good chunk of the cLightMgr class, still a lot missing though:
```C
struct cPenWind
{
    uint8_t direction;
    uint8_t power;
    uint8_t frequency;
    uint8_t unk3;
};
static_assert(sizeof(cPenWind) == 4);

enum class GXAnisotropy : uint8_t
{
    GX_ANISO_1,
    GX_ANISO_2,
    GX_ANISO_4
};

struct cLightMgr_EnvInfo // cLightMgr::GetEnvPtr returns ptr to this, mostly affects Filter01 "LeLit" params
{
    uint32_t amb_color_scroll;
    uint8_t unk4[4];
    uint32_t fog_type;
    float fog_start;
    float fog_end;
    float fog_color;
    uint32_t mirror_fog_type;
    float mirror_fog_start;
    float mirror_fog_end;
    float mirror_fog_color;
    int32_t dof_distance;
    uint8_t unk2C;
    int8_t dof_alpha_level;
    int8_t dof_mode;
    uint8_t blur_rate;
    uint32_t tune[4];
    uint8_t model_tev_scale;
    uint8_t player_tev_scale;
    float fog_far_play; // named FAR_PLAY by GC debug, wtf does FAR_PLAY mean? (color related?)
    uint8_t unk48[148];
    uint8_t unkDC[16];
    cPenWind wind;
    int8_t blur_type;
    uint8_t blur_power;
    uint8_t min_lod;
    uint8_t max_lod;
    GXAnisotropy aniso;
    uint8_t g_cont_level;
    uint8_t g_cont_pow;
    uint8_t g_cont_bias;
    float lod_bias;
    uint32_t amb_color_emobj;
    uint32_t amb_color_effect;
};
static_assert(sizeof(cLightMgr_EnvInfo) == 0x104); // size based on bzero call

class cLightMgr
{
public:
    void* vftable;
    uint32_t unk4;
    uint32_t unk8;
    uint32_t unkC;
    uint8_t unk10;
    struct cLight* lights;
    uint32_t unk18;
    void* room_lit_pointer;
    cLightMgr_EnvInfo env_info;
    uint32_t unkFlagsBuffer124[8];
    uint8_t unk144[32];
    uint32_t path;
    void* core_pointer;  // pointer to int16?
    void* room_pointer1; // pointer to int16?
    void* room_pointer2; // pointer to int16?
    uint32_t unk174;
    int8_t unk178;
    float unk17C;
    uint32_t unk180;
    uint32_t unk184;
    uint32_t unk188;
    uint32_t unk18C;
    float unk190;
    uint8_t unk194[64];

    void setEnv(cLightMgr_EnvInfo* env, int8_t a3)
    {
        cLightMgr__setEnv(this, nullptr, env, a3);
    }
};
// size based on ctor code (same size as GC, but offsets changed some reason?)
static_assert(sizeof(cLightMgr) == 0x1D4); 
```

**Comment by nipkownix** [comment]
Sorry for the lack of feedback on this.

I'll do some testing to see if any corruption happens on my end.

**Comment by emoose** [comment]
Think the issue with keyboard presses being carried across menus should be fixed now, there's a small issue backing out of `AREA JUMP` where it also exits the tool menu too, but that's pretty minor.

IMO this is mostly finished now, can't really think of much else to add atm at least, just need to know whether heap corruption still happens or not...

If anyone reading this wants to try it out, here's a build of latest commit: [re4_tweaks-debug_menu-cf6ba05.zip](https://github.com/nipkownix/re4_tweaks/files/7594641/re4_tweaks-debug_menu-cf6ba05.zip)

**Comment by emoose** [comment]
>Also, minor nitpick, but it seems EnableDebugMenu should be in the [MISC] section of the .ini, right? ReadSettings() appears to be trying to read it from there too.
Oh yeah, not sure how it ended up in MOUSE section lol. I'll fix that & add a note about potential crashes too.

**Comment by nipkownix** [comment]
Sweet! Thank you!

**Pull request merged**
