### PR TITLE
RaiseInventoryAlloc: increase game heap sizes instead of pointing to our own buffers, fixes #58

### LINKED ISSUE #58: RaiseInventoryAlloc: Invisible models for unknown reasons
Example from one user:

image

Seems to be the same issue from a while ago. I sadly still can't reproduce this issue for some reason. Tried starting Mercenaries with wesker on all stages, but the silencer was always visible.

Gotta admit I'm stumped here. Hopefully @emoose could have some idea.

If anyone experiences this issue and can help us testing possible workarounds, please let us know.

### PR DESCRIPTION
**Pull request by emoose**
Seems to solve the invisible items bug, many thanks to qingsheng8848 for posting code for their fix! (and also to everyone that helped debug it with us too!)

Cleaned up code a little, removed pointers/hooks that are no longer needed etc.

Should probably spend some time testing game with these changes to make sure heap increases don't break anything else, if anyone wants to help try them there's a build available here: [dinput8-heapHacks-noConsole-clean.zip](https://github.com/nipkownix/re4_tweaks/files/8035322/dinput8-heapHacks-noConsole-clean.zip)

### CODE REVIEW

**Comment by nipkownix** [comment]
Cool! Awesome work. I'll send a build to albert so he can help testing and see if the chinese issue are fixed as well. Thanks for all your work!

**Comment by emoose** [comment]
^ last commit includes fix for #99

**Comment by nipkownix** [comment]
Albert just reported that the Chinese font issues are gone too 🎉 (turns out it affected Japanese too)
(why did it only affect these languages tho? and why is the ``subScreen`` memory (ss_pzzl stuff) even related to that? Guess it is one of those mysteries we will never know the answer to.

**Comment by nipkownix** [comment]
Guess we're safe to merge this now?

**Comment by laymonage** [comment]
> Guess we're safe to merge this now?

I've been playing with this patch from Chapter 3-1. I'm in Chapter 5-3 now and haven't noticed any issues. I also have the tactical vest and Mafia Leon fixes (made a custom build to include those and this PR) since 5-1. No issues so far.

The silencer was invisible in the inventory and the Merchant until I applied this patch.

**Comment by nipkownix** [comment]
Nice. Thank you, emoose.

Also thank you, @qingsheng8848 for sharing your code with us.

**Pull request merged**
