### PR TITLE
Added option to restore Gamecube title menu control

### PR DESCRIPTION
**Pull request by pas-de-2**
For https://github.com/nipkownix/re4_tweaks/issues/290 and https://github.com/nipkownix/re4_tweaks/issues/318

https://user-images.githubusercontent.com/116680301/206851568-701b1ac3-4fa6-498a-967e-ee5b9e8f9fe0.mp4

Not sure if this was necessarily the best way to do this, but I wound up just writing a replacement titleLoop function.

In the GC version you zoomed in and out with the aim and knife keys. In the PS2/Wii versions, they mapped zoom to up/down right analog stick instead. I went with the PS2/Wii controls, because they're much more intuitive.

I also changed the RestoreDemoVideos key detection behavior to only trigger on active buttons, and not joysticks, like in the console versions.

### CODE REVIEW

**Comment by emoose** [comment]
Awesome! Going with the Wii controls is probably better, seems to work fine with my Xbone controller - I never really played the GC/Wii versions much though so can't really say if it's working the same as those, at least it seems fine though.

Wonder if some kind of KB/M control could be added to it, maybe if mouse button is held it could follow the mouse pointer or something like that, AFAIK `PadRead` does have some code that sets the AnalogXX fields based on mouse movement, but that might only be ran under certain conditions (Del Lago fight?)

**Comment by nipkownix** [comment]
Nice job!

About RestoreDemoVideos: I'm not sure if it is worth it to unset after SPF_KEY after calling KeyStop. SPF_KEY will be set to true once playback starts anyway, right?

**Comment by pas-de-2** [comment]
When watching movies, the game stores all of your STOP flags in a `flags_STOP0_backup_180` inside `cSofdec::initWork`, and then restores them when it's over via `cSofdec::DispReset`. I had to track this down when I noticed the analog stick controls stopped working on the title menu when I quit out of a demo.

**Comment by nipkownix** [comment]
Ah, so the flags are backed up, I see. Thanks for figuring this out!

I assume we can merge this, then?

**Comment by pas-de-2** [comment]
Updated it to use `fAnalog` instead of `Analog`, feels much more like the console versions now without the big right stick deadzone.

I'm not familiar with how the KB/M inputs work. Are you thinking like holding right click to drag? Could do right click + mousewheel to zoom, then.

**Comment by nipkownix** [comment]
>Updated it to use fAnalog instead of Analog, feels much more like the console versions now without the big right stick deadzone.

Should be careful using ``fAnalogRX/Y`` since, IIRC, they don't take any deadzone into consideration and will cause issues when the controller has even the sightliest amount of stick drift.
Seems I used 0.4 as a deadzone in ``LastUsedDeviceHook`` (ControllerTweaks.cpp), and that solved the issues Albert was having. Would probably be safer to use something like that here too.

> I guess Mouse3 to drag then?
I guess MMB could work fine. Or maybe something like holding down CTRL and moving the mouse.
I'm just not sure about the zoom. Hmm.

**Comment by pas-de-2** [comment]
Yep, I borrowed code from `LastUsedDeviceHook`. I set the deadzone to 0.3. It's not completely gone, just noticeably smaller.

**Comment by pas-de-2** [comment]
Going to leave this alone for now if someone wants to try their hand at implementing mouse controls. I took a glance at `PadRead`and my eyes started bugging.

**Comment by nipkownix** [comment]
Cool, guess we'll merge this, then. I do plan on taking a look at implementing mouse controls, but not right now.
Thank you!

**Comment by nipkownix** [comment]
Added KB/M support in ba593cff70e6d5552ef8373969b870bd99ccf0f5. Ended up using our own input funcs since PadRead is a disaster.. :p

**Pull request merged**
