### PR TITLE
Misc: fix some item descriptions in the merchant and examine subscreens

### PR DESCRIPTION
**Pull request by pas-de-2**
https://github.com/nipkownix/re4_tweaks/issues/434

Workaround fix for [the silencer wrongly suggesting it gives the handgun a 5x crit chance](https://user-images.githubusercontent.com/116680301/211691071-2256ad09-a251-4f76-bc44-200203837815.jpg) when the handgun has less than max firepower:

While we're here, remove the infinite bullets description from the unupgraded Chicago Typewriter:

### CODE REVIEW

**Comment by lextra2** [comment]
Nitpick, but why in the second image, is half the text box empty and it looks like it cuts to a new line right in the middle?

**Comment by pas-de-2** [comment]
That's just how it's formatted in the MDT file.
```
{0x0000}  {0x1100}{0x5300}{0x0300}This machinegun is outfitted with a{0x0300}powerful .45 caliber magazine. {0x0800}{0x0100}
```
{0x0300} is a newline character.

It's mostly an artifact of the fact that the font was larger on the lower res GameCube, such that the sentence wouldn't fit on one line:

RB4E08_2023-01-10_23-55-10
We don't have the ability to edit the MDT data in memory yet. This fix is only redirecting what item it thinks is being looked at. In the future we could improve this to eg. restore the Handgun w/ Silencer text.

**Comment by juuuulian-s** [comment]
does this mean some of the unlockables are getting a rebalance/proper upgrade progression?
it always bothered me how quickly you can make the mathilda and the handcannon busted op since every upgrade is available from the get go.

**Comment by nipkownix** [comment]
Very clever workaround! Can't read the code right now, but I imagine you're not spoofing the IDs if the weapons are fully upgraded, right?

**Comment by pas-de-2** [comment]
Yes, it checks for whether the weapon has its exclusive upgrade first, so eg. Wesker's pistol is unaffected.

**Comment by nipkownix** [comment]
Many thanks!

**Pull request merged**
