### PR TITLE
Trainer: added ID Inspector tool for HUD objects

### PR DESCRIPTION
**Pull request by pas-de-2**
The start of an object inspector I put together in order to create this PR https://github.com/nipkownix/re4_tweaks/pull/446

Lets you move around, rescale, and recolor ID objects while ingame. Also organizes them into a tree view so you can see their relationship to one another, and whether an object acts as an anchor or contains an actual texture.

If an ID unit has a `markNo`, that means it was designated for manipulation somewhere in the game's code, like markNo 0xFE here is the small icon that pops up next to NEW GAME to let you know Professional mode's been unlocked.

Anchors can't be scaled, but they can be recolored, [which affects all their child objects](https://user-images.githubusercontent.com/116680301/213862612-9912dd96-c411-486e-8fb6-a275f4075300.jpg).

Modders would probably find this useful if they had some kind of UWF editor. It shouldn't be too hard to make one, the UWF files are just an 8 byte header and data formatted into either ID_DATA_V1 or ID_DATA_V2, depending on whether the header's `Version_0` is 1 or 2. They seem to be organized by [ID Class](https://github.com/nipkownix/re4_tweaks/blob/master/dllmain/SDK/ID.h#L136), so core27.UWF is `IDC_LIFE_METER`, core34 is `IDC_BLLT_ICON`,  core37 is `IDC_LASER_GAUGE`, etc. Pastebin with the structs: https://pastebin.com/NNf8TKi5

### CODE REVIEW

**Comment by lextra2** [comment]
First step for #390 I guess?

**Comment by nipkownix** [comment]
Looks pretty good!
Let me know once this and the other PR are good to merge.
(Sorry for the lack of feedback, been a bit busy preparing for a new job 😅)

**Comment by pas-de-2** [comment]
Congrats on the new job! This should be good to merge, there's more functionality I want to add later on but it's not a priority right now.

**Comment by emoose** [comment]
Good stuff, seems to be working fine on my end with all the EXEs.

Didn't realize the ID units could be organized like that, makes sense seeing as it uses parent/child links - IIRC cModel/cEm/cParts also uses parent/child links too, maybe worth seeing if a tree view would be useful for those some time.

>It shouldn't be too hard to make one, the UWF files are just an 8 byte header and data formatted into either ID_DATA_V1 or ID_DATA_V2

I'm guessing the game is just parsing those ID_DATA structs into `ID_UNIT`? Hopefully can be done in reverse without too much effort, not actually sure if there's already any tools for UWF modding besides hex editing, so maybe could help modders a lot, probably worth looking into later on.

BTW I think the weird `IDC_PRICE_01 | IDC_SSCRN_FAR_0` classes with ORs are just IDA trying to make sense of them out of the IDC defines we have, those might just be new IDC classes that weren't in the PS2 symbols.

Added some placeholder `IDC_UNK_XX` defines in latest DB but didn't try looking into what those classes might actually be for yet, feel free to add new defines for them if you notice any pattern that they get used for.

**Comment by pas-de-2** [comment]
Oh that makes sense, since eg. `IDC_PRICE_01 | IDC_SSCRN_FAR_0` are the CREDITS and QUIT title menu textures that got added later on for the 360/UHD ports. Should we call it eg. `IDC_TITLE_MENU_1`, and rename `IDC_TITLE_MENU` to `IDC_TITLE_MENU_0`, even though they aren't contiguous in the enum?

**Comment by emoose** [comment]
Sure:
```C
enum ID_CLASS
{
  IDC_SSCRN_MAIN_MENU = 0x0,
  IDC_SSCRN_BACK_GROUND = 0x1,
  IDC_SSCRN_PESETA = 0x2,
  IDC_SSCRN_CONFIRM = 0x3,
  IDC_SSCRN_ETC = 0x4,
  IDC_SSCRN_NEAR_0 = 0x10,
  IDC_SSCRN_NEAR_1 = 0x11,
  IDC_SSCRN_NEAR_2 = 0x12,
  IDC_SSCRN_NEAR_3 = 0x13,
  IDC_SSCRN_0 = 0x14,
  IDC_SSCRN_1 = 0x15,
  IDC_SSCRN_2 = 0x16,
  IDC_SSCRN_3 = 0x17,
  IDC_SSCRN_FAR_0 = 0x18,
  IDC_SSCRN_FAR_1 = 0x19,
  IDC_SSCRN_FAR_2 = 0x1A,
  IDC_SSCRN_FAR_3 = 0x1B,
  IDC_SSCRN_CKPT_0 = 0x1C,
  IDC_SSCRN_CKPT_1 = 0x1D,
  IDC_SSCRN_CKPT_2 = 0x1E,
  IDC_SSCRN_CKPT_3 = 0x1F,
  IDC_ACT_BUTTON = 0x20,
  IDC_LIFE_METER = 0x21,
  IDC_GAUGE = 0x22,
  IDC_COUNT_DOWN = 0x23,
  IDC_BINOCULAR = 0x24,
  IDC_SCOPE = 0x25,
  IDC_EXAMINE = 0x26,
  IDC_DATA = 0x27,
  IDC_TITLE = 0x28,
  IDC_TITLE_MENU = 0x29,
  IDC_OPTION = 0x2A,
  IDC_OPTION_BG = 0x2B,
  IDC_EVENT = 0x2C,
  IDC_DEAD = 0x2D,
  IDC_CONTINUE = 0x2E,
  IDC_MSG_WINDOW = 0x2F,
  IDC_CINESCO = 0x30,
  IDC_WIP = 0x31,
  IDC_BLLT_ICON = 0x32,
  IDC_SUB_MISSION = 0x33,
  IDC_LASER_GAUGE = 0x34,
  IDC_CAMERA_BATTERY_MB = 0x35,
  IDC_NUM_00 = 0x40,
  IDC_NUM_61 = 0x7D,
  IDC_PRICE_00 = 0x80,
  IDC_PRICE_01 = 0x81,
  IDC_PRICE_02 = 0x82,
  IDC_PRICE_03 = 0x83,
  IDC_PRICE_04 = 0x84,
  IDC_UNK_99 = 0x99,
  IDC_UNK_A0 = 0xA0,
  IDC_UNK_AA = 0xAA,
  IDC_TOOL = 0xFE,
  IDC_ANY = 0xFF,
};
```
I think the only adds there were the `UNK_99/UNK_A0/UNK_AA` ones, but game might be using more than those.

(did post an updated IDB here a little while ago that had those too, but can't remember which post that was inside now... maybe will update re4-research soon)

>Should we call it eg. IDC_TITLE_MENU_1, and rename IDC_TITLE_MENU to IDC_TITLE_MENU_0, even though they aren't contiguous in the enum?

Sounds fine to me if it's just continuing an existing class, for completely new ones you can just go with whatever you guess for it (with `_mb`, like `IDC_CAMERA_BATTERY_MB`, which oddly wasn't inside PS2 at all)

**Comment by nipkownix** [comment]
Thank you again, @pas-de-2! And sorry for the delay, getting used to my new job has been taking all my time :p

**Pull request merged**
