### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by nipkownix**
@emoose Could you give me your opinion on this PR draft? This makes some changes I've been meaning to make for some time. Biggest change being the wrappers, but I'm also _trying_ to improve support for running from paths that contain UTF-8 chars.

While messing with the game on Linux, I noticed that the game crashes on start if the path it is running from contains special characters such as Japanese words. Before I could even dig into that issue, I realized something else: re4_tweaks itself was also having some trouble with special chars in paths.
I've changed some of our stuff to use ``wstring`` instead, but some other issues remain: I couldn't get our .ini reader to read files inside a path with special chars. There's also the ``looseFilePath`` from our sideload feature, which I haven't tested with special chars yet, but I imagine it wouldn't work as is.

Of course, none of this special/UTF-8 chars stuff is really important right now _unless_ we can make the game itself run from paths with those. (Do people even do that normally? Regardless, I imagine the game might also fail to load its own config.ini from the Documents path if the user's account name contains special chars..)

Do you think any of these things would be best left as is? The wrappers seem to be working nicely (from my tests). The ``wstring`` changes also aren't hurting, but they're pretty much useless right now, so no worries if we end up discarding this PR.

Ah, this should also fix the LNK4098 warning related to freetype. I noticed you pushed a workaround in 9bccd1ffbd3352c9f239cdc9cb6fde3bea981bf6 earlier. Turns out the problem was my fault for not including a debug version of the .lib as well. Sorry about that :p

### CODE REVIEW

**Comment by emoose** [comment]
Haven't been able to look through it much yet, though from what I've read std::string should mostly work fine with UTF-8 already, other than doing doing things like string splits/regexes which might need extra handling, but don't think we really use those on file paths anyway.

Our std::string/c_str()/char* uses probably do end up calling some Win32 xxxA funcs though, on Windows those recently had UTF-8 support added in ~Win10 (but might require a manifest flag to activate), don't know if WINE/Pluton supports that at all yet, if not then changing to wstring/wchar_t/xxxW is probably the better choice.

**Comment by nipkownix** [comment]
>  from what I've read std::string should work fine with UTF-8 already though

True, yeah. I decided to move try and move to wstring/wchar because of the weirdness you mentioned. Seems UTF8 with regular strings should work fine as long as whatever you're passing it to knows/expects that the string is going to be UTF8-encoded. The ini reader, for example, doesn't do that, apparently ._.
I've read C++ 20 has better support for that, with stuff like ``char8_t``, but moving to the ``w`` version of things seemed like a better idea (plus yeah, I've seen Silent's patches doing the same :p)

**Comment by nipkownix** [comment]
Just rebased this onto the trainer branch to make it easier to test/make changes.

**Comment by nipkownix** [comment]
@emoose Just pushed the DXVK stuff. ~hopefully building it there works correctly.~
Just one issue: DXVK source files compile with _tons_ of warnings on MSVC. Not sure if there's a way to suppress warnings for an entire folder or something like that. Do you happen to know of a way to do it?

It would be nice to also have a way to test if the user's system supports Vulkan, and fallback to d3d9 if it isn't available. Haven't looked into that yet.

Anyway, seems it does improve performance:

image


image

**Comment by emoose** [comment]
You can select multiple files and open properties window to change settings on them all, can maybe just add the warnings to "Disable Specific Warnings" for them.

Think that only needs to be applied to the .cpp files of it, and maybe any of our .cpp that include dxvk stuff too (unless we edit whatever headers they include)

**Comment by emoose** [comment]
Had a quick look through the code, the new namespacing seems pretty nice, `re4t::init::XXX` for the init funcs of each part makes sense, I guess for stuff like trainer where we have Trainer_Init & Trainer_Update etc we can just have an `re4t::trainer` namespace to handle it too.

There's also a few things I've been meaning to fix up, just some ideas to make things tidier, will probably try fixing them after we merge this refactor (but if anyone wants to look into them feel free):
- Move game function & struct defs from the dllmain/*.cpp files (besides Game.cpp) into SDK folder instead (with `bio4` namespace for funcs), and any code that finds func addrs in the game EXE to Game.cpp too.
- For hooks that are just hooking in order to run some code before a function & then return to orig func, could maybe save on some func typedefs by using `injector::hook_back`, haven't seen it well documented though, but https://github.com/ThirteenAG/GTA-One-Liners/blob/feb6906af100b6c069311df167ac7920f26deafc/plugins/source/bully.cpp gives an example of it (ctrl+f `hbsub_6900C0`)
- Think I've seen some places where we still access things with offsets directly (`bleh = *(uint8_t*)(class + 0x1337)`) - might have the structs for some of those in SDK now, would be better to change over to those.
- Game.h includes all the SDK headers right now, so when a .cpp includes Game.h it pulls in a lot of stuff which might not be needed for it - probably be better to remove the big include block there and just include from SDK whatever the .cpp needs.

**Comment by nipkownix** [comment]
> You can select multiple files and open properties window to change settings on them all, can maybe just add the warnings to "Disable Specific Warnings" for them.

Ah cool. Had no idea we could do it per file like that. Seems it does get rid of the warnings. Thanks!

> (E2: hmm, https://github.com/nipkownix/re4_tweaks/pull/255 also gets around the same FPS as vulkan did too, maybe something else is bottlenecking it to that FPS...)

Hmm, do you think there would be any issue when using #255 with vulkan?

> (E3: seems like it's CPU limited due to something, at least reducing CPU clock did reduce both VK & https://github.com/nipkownix/re4_tweaks/pull/255 the same, wonder if we can get some kind of profiler to work with the fakepdb...)
Gonna see if I can dig something up. I remember doing something similar on Wine once.

> There's also a few things I've been meaning to fix up, just some ideas to make things tidier, will probably try fixing them after we merge this refactor (but if anyone wants to look into them feel free):

Nice! I've read about ``injector::hook_back`` before, but never really tried to use it.
I think being explicit about ``__cdecl`` is a good idea because of other compilers, as you mentioned. Never a good idea to rely on defaults being the "default" forever, I guess :p

Btw, I think you should be able to push to this branch, right? If not, I can just merge this right now to net get in your way.

Been thinking about just going ahead and merging #255, even though not many people tested it so far. Do you think we should be safe-ish to do that?

**Comment by emoose** [comment]
Yeah we'd probably be fine merging #255, I never had any issues with it at least, what do you think of making MultithreadFix enabled by default too? Maybe a better chance of finding out if there are any problems with it with certain configurations.
(could add a big note in INI about disabling it in case of issues too)

Still need to add some cfgMenu options for that too, I'll add that now.

About dxvk, it seems to be fine with the 1.10.3 release at least, haven't tried it with our async enabled ver though.
I think it should be fine though, might have read somewhere that the D3DCREATE_MULTITHREADED flag doesn't actually get used for anything in DXVK (but could be wrong about that), so maybe wouldn't make any difference besides adding mutex locks.

**Comment by nipkownix** [comment]
> (E: updated it, also moved to framerate section & made it default enabled, let me know if you think it should be disabled instead)

Sounds good to me. I was about to suggest leaving it enabled by default.

**Comment by nipkownix** [comment]
Just merged the MT fix here and did some testing in the cave area after the village:

VK + MT fix enabled: 470 fps
d3d9 + MT fix enabled: 340 fps

Quite a nice improvement, even if it changed depending on the area your in or you camera angle.

**Comment by nipkownix** [comment]
Ah, by the way, just noticed ``ReplaceFramelimiter`` is in the Display section, not the Frame Rate one. Guess we should move it?

**Comment by emoose** [comment]
Ah I was thinking of moving that to frame rate too, would probably make more sense there.

Is that `ImproveWater` fix new? Does it help with https://github.com/nipkownix/re4_tweaks/issues/175#issuecomment-1243043667 maybe?

BTW just wondering, have you started on any changelog for the stuff after 1.7.7.6? I'm not even sure where to start with that lol, I guess we can just look through the commits since that release: https://github.com/nipkownix/re4_tweaks/compare/1.7.7.6...master

**Comment by nipkownix** [comment]
> Is that ImproveWater fix new? Does it help with the water bug you mentioned before maybe? (https://github.com/nipkownix/re4_tweaks/issues/175#issuecomment-1243043667)

Ah, yes, it does help with that. It is a "new" fix, but I've had it in a local branch more or less ever since I posted that comment. It makes the water much more similar to the GC version, but I have an impression that the workaround isn't a 1-1 perfect match with GC. Still much better than the jelly water, though :p

> BTW just wondering, have you started on any changelog for the stuff after 1.7.7.6?

Ouch, 200 commits since then? lol
I haven't started it yet. I guess I can come up with something later today, unless you want to do it yourself.

**Comment by nipkownix** [comment]
@emoose, here's what I got so far for the changelog:

```
- Added EnableModExpansion: Enables patches/hooks for expanded modding capabilities, such as allowing enemy speed & scale to be defined when spawning. (See https://github.com/nipkownix/re4_tweaks/wiki/Modding-Enhancements#mod-expansion for more info)

- Added CameraImprovements: Provides a small set of camera tweaks (KB/M only)

- MouseTurning: Added new MouseTurning type, enabled by default. The original mode (Type B), is still available in the config menu.

- OverrideCostumes: Workaround crashes due to missing inventory models for some of Ada's costumes. (#309)

- Added new Trainer tab with features such as invincibility, heal player/Ashley, free camera, weapon hotkeys, no-clip, Em Manager, flag editor, Debug Tools (area jump, etc), Inventory Item Adder and more.

- Added command-line params support. (See https://github.com/nipkownix/re4_tweaks/wiki/Modding-Enhancements#command-line-parameters for more info)

- EnableGCBlur: Add new blur mode, slightly improved to look better on modern high-definition displays.

- AllowReloadWithoutAiming: Change hook to prevent aiming issues under certain conditions. (#314)

- Added ReplaceFramelimiter: implements new reduced-CPU-usage limiter

- Added DebugDisplay: recreates effect of DBG_SAT_DISP & DBG_EAT_DISP flags

- re4_tweaks UI: Added high-DPI support 

- Fixed face morphing (PlSetFace), fixing the bug with face animations not being shown during gameplay

- Added hook to allow the Merchant's item list to skip to top/bottom when going past bounds of the list

- Added re4_tweaks AutoUpdater

- Improved SkipIntroLogos

- Added SkipMenuFades

- Added RestoreGCSoundEffects: Restores certain sound effects that were changed from the original GC release. (currently only changes sound of the knife)

- Fixed melee range firing bug with type III controls

- Added MultithreadFix: Enables fixes for multithreaded DirectX9, giving a slight performance boost

- Added UseVulkanRenderer: Enables the use of the DXVK-based vulkan renderer, which provides better performance on newer hardware

- Added ImproveWater: Improves some of the water effects, fixing the "jelly-like" water that is present in some areas.

- FrameLimiter: Workaround flickering/shaky r117 chandelier

- FixFallingItemsSpeed: Properly fixed treasure falling speed and added a fix for the falling speed of door locks 

- Added FixCompartmentsOpeningSpeed: Fixes the speed of opening compartments such as drawers, cabinets, chests, boxes, shelves, etc.

- Added FixMovingGeometrySpeed: Fixes the speed of moving geometry such as: doors, passages, gates, ceilings, etc.

- Added RestoreDemoVideos: Restores the playback of demo videos that play when the game is idle at the main menu or the "press any key" screen for about 20 seconds. More info in the config menu/.ini file.
```

Should probably go more in-depth about all the trainer features, though. Besides that, I _think_ I haven't missed anything?

There also PR #369. I'm not sure if that's ready to merge yet. 
@pas-de-2, I guess we still have to fix that non-English languages issue, right?

**Comment by pas-de-2** [comment]
Yeah, it's just a relatively minor issue that I got stuck on. Everything else tested okay.
If you wanted to put out a release soon it should be okay to merge, and add a TODO to the tracker.

**Comment by emoose** [comment]
Made a quick WIP of changelog for the trainer, feel free to edit if wanted (or disregard if you already started on one :p)

```
- Added Trainer section to re4_tweaks menu, this optionally allows players to change various parts of the game, such as:
 - Weapon Hotkeys: allows switching weapons without needing to open inventory, by default assigns keys 1 - 5 to different weapon categories, alternatively weapons can be assigned to one of these keys directly by highlighting them in inventory and pressing the hotkey.

 - Inventory Manager: allows viewing a list of all inventory contents & editing values for certain items (eg. item stack count, weapon upgrade values), can also add items to inventory via a simple list selection (without needing to set up slots for each item seperately), inventory can also be exported to & imported from an easily editable JSON format.

 - Trainer patches: Invincibility / Weak Enemies / Infinite Ammo / Disable Enemy Targeting / Disable Collision / Free Camera / Player Speed Override / Difficulty Level Override / Enemy HP multiplier / Ashley Presence Override / Disable Enemy Spawns / Disable Bodies from disappearing / Allow Exit without Ashley / Enable unused DebugTrg function.

 - Hotkeys that allow assigning key presses to certain trainer functions: Toggle Noclip / Toggle Speed Override / Toggle Free Camera / Move Ashley to Player / DebugTrg trigger combination.

 - Flag Editor: allows tweaking certain internal game flags, such as certain debug features, progression in the level, and editing the unlockables earned.

 - Em Manager: can list all `cEm` (enemy) instances on the level, and allow viewing certain information about them; info can also be undocked from the main re4_tweaks UI & made visible during gameplay too.

 - ESP: allows drawing info about enemies on top of them during gameplay, without needing to open seperate UI windows - can be configured to display many different pieces of info about the enemy (health bars, current AI routine, other debug info...), and can also draw info about all active cEms in range on the side of the screen.

 - Area Jump: allows teleporting to different rooms in the game (including certain test/debug levels which were accidentally included)

 - Filter Tool: lets you adjust certain post-processing effects in the game, mainly to help with testing improvements to these filters.

 - Globals: shows a seperate UI window that lists certain important internal information about the game, such as room number, dynamic difficulty points & level, current game routine, current HP for both player & ashley - useful when debugging certain mods.
```

**Comment by nipkownix** [comment]
Just pushed some changes to settings, mainly moving some stuff to the new Overrides tab. Should probably make sure everything is still saving/loading fine and that I've missed nothing.
We should probably be good for another release after that 😅

**Comment by pas-de-2** [comment]
What do you think of creating a `Gameplay` tab to help clean up the `Misc` tab? It's getting kind of overstuffed in there.

gameplay-tab

**Comment by nipkownix** [comment]
Huh, sounds like a good idea to me, actually. I remember being against adding new tabs in the past (before the UI redesign, I think it had something to do with that?) for some reason, but even the Trainer tab wasn't a thing back then.

**Comment by pas-de-2** [comment]
Sure, up

**Comment by nipkownix** [comment]
Updated changelog:

```
### **Note: This update changed some sections of the .ini structure, so you will notice that some of your existing settings will revert to default.**

- Added EnableModExpansion: Enables patches/hooks for expanded modding capabilities, such as allowing enemy speed & scale to be defined when spawning. (See https://github.com/nipkownix/re4_tweaks/wiki/Modding-Enhancements#mod-expansion for more info)
- Added CameraImprovements: Provides a small set of camera tweaks (KB/M only)
- MouseTurning: Added new MouseTurning type, enabled by default. The original mode (Type B), is still available in the config menu.
- OverrideCostumes: Workaround crashes due to missing inventory models for some of Ada's costumes. (#309)
- Moved OverrideCostumes to the Trainer tab. (Overrides)
- Added command-line params support. (See https://github.com/nipkownix/re4_tweaks/wiki/Modding-Enhancements#command-line-parameters for more info)
- EnableGCBlur: Add new blur mode, slightly improved to look better on modern high-definition displays.
- AllowReloadWithoutAiming: Change hook to prevent aiming issues under certain conditions. (#314)
- Added ReplaceFramelimiter: implements new reduced-CPU-usage limiter
- Added DebugDisplay: recreates effect of DBG_SAT_DISP & DBG_EAT_DISP flags
- re4_tweaks UI: Added high-DPI support 
- Fixed face morphing (PlSetFace), fixing the bug with face animations not being shown during gameplay
- Added hook to allow the Merchant's item list to skip to top/bottom when going past bounds of the list
- Added re4_tweaks AutoUpdater
- Improved SkipIntroLogos
- Added SkipMenuFades
- Added RestoreGCSoundEffects: Restores certain sound effects that were changed from the original GC release. (currently only changes sound of the knife)
- Fixed melee range firing bug with type III controls
- Added MultithreadFix: Enables fixes for multithreaded DirectX9, giving a slight performance boost
- Added UseVulkanRenderer: Enables the use of the DXVK-based vulkan renderer, which provides better performance on newer hardware
- Added ImproveWater: Improves some of the water effects, fixing the "jelly-like" water that is present in some areas.
- FrameLimiter: Workaround flickering/shaky r117 chandelier
- FixFallingItemsSpeed: Properly fixed treasure falling speed and added a fix for the falling speed of door locks 
- Added FixCompartmentsOpeningSpeed: Fixes the speed of opening compartments such as drawers, cabinets, chests, boxes, shelves, etc.
- Added FixMovingGeometrySpeed: Fixes the speed of moving geometry such as: doors, passages, gates, ceilings, etc.
- Added LimitMatildaBurst: Limit the Matilda to one three round burst per trigger pull.
- Added RifleScreenShake: Adds a screen shake effect when firing a rifle.
- Added RestoreDemoVideos: Restores the playback of demo videos that play when the game is idle at the main menu or the "press any key" screen for about 20 seconds. More info in the config menu/.ini file.
- Added SeparateWaysProfessional: Adds a menu to choose between Normal and Professional difficulty modes when starting a new game of Separate Ways.
- Added RestoreAnalogTitleScroll: Restores the ability to manipulate the background scroll of the post-new game title menu with the right analog stick or mouse movement.
- Added AlwaysShowOriginalTitleBackground: After beating the game, force the game to always show the original main menu background image of Leon and Ashley.
- Added ShowGameOutput: Displays the game's original logs/debug output into a console window.

Introducing the new (optional) Trainer section in the re4_tweaks config menu! This section allows you to modify various aspects of the game during gameplay, such as:
- Trainer patches: Enable invincibility, weak enemies, infinite ammo, disable enemy targeting, disable collision, free camera, disable enemy spawns, disable bodies from disappearing, allow exiting area without Ashley, and enable the unused DebugTrg function.
- Trainer overrides:  Player speed override, game difficulty override, dynamic difficulty level override, enemy HP multiplier, and Ashley presence override.
- Weapon hotkeys: Switch weapons by pressing specific keys without needing to open the inventory first. By default, keys 1-5 are assigned to cycle through weapons in different categories. Alternatively, you can assign a specific weapon to a hotkey by highlighting it in the inventory and pressing the corresponding key.
- Inventory manager: View a list of all items in your inventory and edit certain values, such as stack count and weapon upgrade values. You can also add new items to your inventory by selecting them from a simple list, without needing to set up slots for each item separately. The inventory can also be exported to or imported from an easily editable JSON file.
- Hotkeys: Allows binding specific key presses to trigger certain trainer patches or functions.
- Flag editor: Tweak internal game flags, such as flags for debug features, level progression, and unlockables earned through gameplay.
- Em Manager: View a list of all "cEm" (enemy) instances in the current level and edit certain information about them. The info can also be undocked from the main re4_tweaks UI and made visible during gameplay.
- ESP: Display information about enemies on top of them during gameplay, without requiring you to open separate UI windows. It can be configured to display various pieces of information about the enemy, such as health bars, current AI routine, and other debug info. Can also draw information about all active enemies in range to the side of the screen.
- Area jump: Teleport to different rooms in the game (including certain test/debug levels that were accidentally included)
- Filter tool: Adjust post-processing effects in the game, mainly to help with testing improvements to these filters.
- Globals: Show a separate UI window that lists important internal information about the game, such as the current room number, dynamic difficulty points and level, current game routine, and current HP for both the player and Ashley. (May be useful for mod developers when debugging their mods.)
```

Just gotta make sure everything is saving/loading fine, and that I haven't missed anything from the changelog.

**Comment by emoose** [comment]
@nipkownix looks like a couple PRs might be missing there, I think it's just these in the pic + the NTSC difficulty setting:
image

**Comment by nipkownix** [comment]
Oh yeah, we're missing the Saddler fix and NTSC mode. Nice catch!

**Comment by emoose** [comment]
Good job with the release, great to see we made it in time for Christmas 🥳 

I added a tiny section in the release text about updating from HD Project 1.1, think the instructions there should be correct, but feel free to change it if not. (mostly only added that section because some other sites like PCGW used to mention deleting all re4_tweaks files before updating, which I don't think we want :P)

Anyway have a good Christmas!

**Comment by nipkownix** [comment]
Thanks!

> I added a tiny section in the release text about updating from HD Project 1.1, think the instructions there should be correct, but feel free to change it if not. (mostly only added that section because some other sites like PCGW used to mention deleting all re4_tweaks files before updating, which I don't think we want :P)

Ohh, nice thinking. I'll probably copy that over to the Nexus pages too. Thank you, and have a good Christmas as well!

**Pull request merged**
