### PR TITLE
Add GitHub Actions workflow to build the project

### PR DESCRIPTION
**Pull request by laymonage**
Thanks for all the hard work! I'm not familiar with C++ and reverse engineering, so I tried to find another way to contribute.

This adds a GitHub Actions workflow to automatically build the project (with both `Debug` and `Release` configurations) and upload both DLL outputs as an artifact. Might be useful to let other people test new commits and PRs, while also ensuring reproducible builds of the project.

I don't know if this setup is sufficient, though. I might be missing some options to `msbuild`.

We can also automate the release with something like [action-gh-release](https://github.com/softprops/action-gh-release), but I suppose you probably want to do it manually so you can test things out ~~(and add the `.ini` as it seems to be written manually?)~~

The result is something like this (you can download the artifact): https://github.com/laymonage/re4_tweaks/actions/runs/1822496969

Let me know if you want me to make adjustments or add some other steps to the build process.

### CODE REVIEW

**Comment by laymonage** [comment]
Oh I just noticed you already added an AppVeyor integration in the latest commit...

**Comment by nipkownix** [comment]
Thank you! I've been thinking about looking into GitHub Actions for a while.

>Oh I just noticed you already added an AppVeyor integration in the latest commit...

Ah, that was just a test. I was trying to see how much work it would take to build the project using mingw-w64 in there, but quickly gave up.

> We can also automate the release with something like [action-gh-release](https://github.com/softprops/action-gh-release), but I suppose you probably want to do it manually so you can test things out (and add the .ini as it seems to be written manually?)

Yeah, usually I think releases are better done manually.
About the .ini, the default one is in `/settings/settings_string.h`, but it is inside a const char. Not sure how difficult/possible it would be to get only the actual settings and move them to an ini file during build. I know some people use lua or python scripts for that, but I havent looked into it.

> Let me know if you want me to make adjustments or add some other steps to the build process.

I think everything looks fine. @emoose any suggestions?

**Comment by laymonage** [comment]
> Yeah, usually I think releases are better done manually. About the .ini, the default one is in `/settings/settings_string.h`, but it is inside a const char. Not sure how difficult/possible it would be to get only the actual settings and move them to an ini file during build. I know some people use lua or python scripts for that, but I havent looked into it.

Thanks. I added a small `awk` script to extract the string and put it in `dinput8.ini`. [It seems to work.](https://github.com/laymonage/re4_tweaks/suites/5250408180/artifacts/161764181) As long as it starts at line 2, column 37 and the last line ends with `)"""";` :laughing:

I'm not a shell script expert so that might not be the best solution, but that's much faster than having to set up Python on the runner.

**Comment by laymonage** [comment]
Also, it seems that the console is enabled even when building with `/p:Configuration=Release` 🤔

**Comment by laymonage** [comment]
> Yeah, it just adds and empty new line at the very top and bottom of the generated .ini file, but I went ahead and pushed some changes to make `WriteSettings` skip that line. The bottom one will still be there, but it is no big deal.

Great, thanks. The bottom one is actually not a problem because text files are supposed to end with an empty newline (though it's mostly no longer needed these days).
 
> Hmm, that's because we `#define VERBOSE` in `dllmain.h` by default.

How do you usually build for `Release`? Do you manually remove that line? If so, I added a step just before the release build to do just that.

> Not seeing that prompt, for some reason.

Hmm, then I guess new workflows can only be added by maintainers of the repo.

One thing I noticed is that you need to login to download the artifacts, so this is only directly useful for those who have a GitHub account. But I guess we can just attach the file to a comment if we need to share it publicly.

**Comment by nipkownix** [comment]
> How do you usually build for Release? Do you manually remove that line? If so, I added a step just before the release build to do just that. Seems to work just fine.

Yeah, I just comment that line out, so we should be fine then.

>One thing I noticed is that you need to login to download the artifacts, so this is only directly useful for those who have a GitHub account. But I guess we can just attach the file to a comment if we need to share it publicly.

Yeah, true.
Thank you! Let me know if you want this merged now. Might want to wait for emoose's input, dunno.

**Comment by laymonage** [comment]
> Yeah, true. Thank you! Let me know if you want this merged now. Might want to wait for emoose's input, dunno.

No worries. I don't have anything to add atm, but let's wait for emoose.

**Comment by emoose** [comment]
Looks good to me, nice use of head/tail to make the INI too, If I'd tried it probably would have ended up with a 30+ line script lol.

**Comment by nipkownix** [comment]
Uh oh, merged this right before leaving for class, but it looks like the build is failing :/

**Comment by laymonage** [comment]
> Uh oh, merged this right before leaving for class, but it looks like the build is failing :/

Huh, weird, looks like we got unlucky. It seems that GitHub is in the process of gradually upgrading the `windows-latest` image from `windows-2019` to `windows-2022` (https://github.com/actions/virtual-environments/issues/4856#issuecomment-1034087279). The build seems to work on [Windows 2022](https://github.com/laymonage/re4_tweaks/runs/5149771950) but not [Windows 2019](https://github.com/laymonage/re4_tweaks/runs/5149770653) due to incompatible VS versions. Let me make the PR to use `windows-2022`.

**Pull request merged**
